spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.124.101/test
    username: root
    password: 123456
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=5,maximumSize=10,expireAfterAccess=5s
  redis:
    host: 192.168.124.101
    port: 6379
    client-type: lettuce
  mail:
    default-encoding: utf-8 #默认编码格式
    host: smtp.qq.com #邮件服务器地址
    port: 465 #端口号
    username: lemonpuer@foxmail.com
    password: cgageqwztzrsbjbj
    properties:
      mail:
        debug: true #启动debug调试
        smtp:
          starttls:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置


logging:
  level:
    workspace: debug