spring:
  #  mvc:
  #    static-path-pattern: /hello/**
  web:
    resources:
      static-locations: [ classpath:/static/ ]
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver