server:
  port: 9005

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: pay_service   #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:9001          #匹配后提供服务的路由地址
          uri: lb://pay-service               #根据服务名称进行负载均衡的路由地址
          predicates:
            - Path=/payService/**      # 断言，路径相匹配的进行路由
            - After=2024-01-05T15:10:03.685+08:00[Asia/Shanghai]          # 表示在设置时间点之后可以访问
            - Before=2024-02-05T15:10:03.685+08:00[Asia/Shanghai]         # 表示在设置时间点之前可以访问
            - Between=2020-02-02T17:45:06.206+08:00[Asia/Shanghai],2020-03-25T18:59:06.206+08:00[Asia/Shanghai]  # 表示在两个时间点之间可以访问
            - Cookie=username,asdf      # 表示必须带上指定cookie: username=asdf 才能访问通过该路由地址转发的服务
            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            - Host=**.test.com          # 需要指定请求的目标主机的域名或IP地址
            - Method=GET                # 指定请求方式
            - Query=username, \d+  # 要有参数名username并且值还要是整数才能路由
          filters:
            - StripPrefix=1       #表示去掉一层前缀；即转发的真实前缀为 /**

eureka:
  instance:
    hostname: gateway-service
    instance-id: gateway-service:9005
    prefer-ip-address: true     #访问路径可以显示IP地址
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka